name: compile_prerelease
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  compile_prerelease:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize submodules
        uses: snickerbockers/submodules-init@v4

      - name: Compile MicMute
        uses: SaifAqqad/GitHub-Action-Ahk2Exe@main
        with:
          in: '.\src\MicMute.ahk'
          out: '.\MicMute.exe'

      - name: Calculate file hash
        shell: pwsh
        run: (Get-FileHash '.\MicMute.exe').Hash  | Tee-Object -FilePath  .\MicMute.sha256;
      
      - uses: actions/upload-artifact@v3
        with:
          name: MicMute
          path: ./MicMute.*

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_commit"
          prerelease: true
          title: "Development Build"
          files: |
            MicMute.exe
            MicMute.sha256
